spring.datasource.url=${SPRING_DATASOURCE_URL:${JDBC_DATABASE_URL:}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${JDBC_DATABASE_USERNAME:}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${JDBC_DATABASE_PASSWORD:}}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_DIALECT:}
server.port=${PORT:10000}

spring.mail.host=${SMTP_HOST:}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME:}
spring.mail.password=${SMTP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

twilio.account-sid=${TWILIO_ACCOUNT_SID:}
twilio.auth-token=${TWILIO_AUTH_TOKEN:}
twilio.from-number=${TWILIO_FROM_NUMBER:}
